server:
  port: 8080
spring:
  application:
    name: aston_project
  datasource:
    url: jdbc:postgresql://localhost:5432/aston_project
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          covid-client:
            url: "https://disease.sh/v3/covid-19/countries"
            logger-level: full
            read-timeout: 5000
            connect-timeout: 5000
          yandex-search-api:
            url: "https://search-maps.yandex.ru/v1"
            logger-level: full
            default-query-parameters:
              apikey: ${YANDEX_KEY}
              lang: "ru_RU"
            connect-timeout: 5000
            read-timeout: 5000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    aston_project: DEBUG
  file:
    name: appLog.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  subject: ${JWT_SUBJECT}}
  issuer: ${JWT_ISSUER}

security: enabled

mail:
  password: ${MAIL_PASSWORD}
  username: ${MAIL_USER}