server:
  port: 8080
spring:
  application:
    name: aston_project
  datasource:
    url: jdbc:postgresql://localhost:5432/aston_project #установите phAdmin4, создайте database с именем aston_project
    username: ${DB_USER} #создайте в phAdmin4 roles и пропишите имя и пороль. В настройках  базы(aston_project) owner укажите эту роль
    password: ${DB_PASSWORD} #я для простоты так и создала root/pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate: #при старте хибер делает импорт сущностей в бд как вы ему тут сказали:
      ddl-auto: validate #create-drop(создает при старте и удаляет при окончании работы), create(просто создает), none(ничего не делает)
  cloud:
    openfeign:
      client:
        config:
          covid-client:
            url: "https://disease.sh/v3/covid-19/countries"
            logger-level: full
            read-timeout: 5000
            connect-timeout: 5000
          yandex-search-api:
            url: "https://search-maps.yandex.ru/v1"
            logger-level: full
            default-query-parameters:
              apikey: ${YANDEX_KEY}
              lang: "ru_RU"
            connect-timeout: 5000
            read-timeout: 5000

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"
    aston_project: "debug"
    #file:
    #name: appLog.log
  pattern: #Для разработки можете отключить записть в файл, поставив перед file решетку
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  subject: ${JWT_SUBJECT}
  issuer: ${JWT_ISSUER}

security: enabled # Можем отключить для разработки

mail:
  password: ${MAIL_PASSWORD:password}
  username: ${MAIL_USER:user}