server:
  port: 8080
spring:
  application:
    name: aston_project
  datasource:
    url: jdbc:postgresql://localhost:5432/aston_project #установите phAdmin4, создайте database с именем aston_project
    username: sample #создайте в phAdmin4 roles и пропишите имя и пороль. В настройках  базы(aston_project) owner укажите эту роль
    password: sample #я для простоты так и создала root/pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate: #при старте хибер делает импорт сущностей в бд как вы ему тут сказали:
      ddl-auto: none #create-drop(создает при старте и удаляет при окончании работы), create(просто создает), none(ничего не делает)
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"
    aston_project: "debug"
  #file:
    #name: appLog.log
  pattern: #Для разработки можете отключить записть в файл, поставив перед file решетку
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"