databaseChangeLog:
  - changeSet:
      id: create-insert-product-type
      author: Kirill Zemlyakov
      changes:
        - createTable:
            tableName: PRODUCT_TYPE
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: "pk_product_type"
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
                    unique: true
        - sqlFile:
            path: db/script/insert-product-type.sql
            encoding: UTF-8